import { ProfileReport } from './types';

export function getMockReport(): ProfileReport {
  return {
    datasetName: 'customer_transactions_2024.csv',
    uploadedAt: new Date().toISOString(),
    summary: {
      rowCount: 847293,
      columnCount: 11,
      fileSizeBytes: 124857600,
      memoryUsageMB: 142.3,
    },
    overallHealth: {
      overall: 73,
      completeness: 81,
      consistency: 68,
      validity: 70,
    },
    attentionItems: [
      {
        severity: 'critical',
        columnName: 'customer_email',
        message: '23% of email addresses fail validation pattern',
      },
      {
        severity: 'warning',
        columnName: 'transaction_amount',
        message: '47 outliers detected beyond 3 standard deviations',
      },
      {
        severity: 'warning',
        columnName: 'postal_code',
        message: 'High null rate (31%) may impact geographic analysis',
      },
    ],
    columns: [
      {
        name: 'customer_email',
        inferredType: 'string',
        declaredType: 'VARCHAR(255)',
        nullCount: 12847,
        nullPercentage: 1.52,
        uniqueCount: 234891,
        uniquePercentage: 27.72,
        healthScore: 42,
        flags: ['type_mismatch', 'suspicious_pattern'],
        topValues: [
          { value: 'test@example.com', count: 1247, percentage: 0.15 },
          { value: 'admin@company.com', count: 892, percentage: 0.11 },
          { value: 'noreply@service.com', count: 743, percentage: 0.09 },
        ],
        insights: [
          '23% of values fail RFC 5322 email validation',
          'Detected 1,247 test/placeholder emails',
          'Consider implementing stricter input validation',
        ],
      },
      {
        name: 'transaction_amount',
        inferredType: 'float',
        declaredType: 'DECIMAL(10,2)',
        nullCount: 0,
        nullPercentage: 0,
        uniqueCount: 84729,
        uniquePercentage: 10.0,
        healthScore: 68,
        flags: ['outliers_detected'],
        numericStats: {
          mean: 127.43,
          median: 89.99,
          stdDev: 234.18,
          min: 0.01,
          max: 9847.32,
          q25: 42.50,
          q75: 156.78,
        },
        distribution: {
          bins: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
          counts: [342891, 287432, 124783, 52847, 23891, 9847, 3421, 1523, 892, 766],
        },
        topValues: [
          { value: '99.99', count: 23847, percentage: 2.81 },
          { value: '49.99', count: 18923, percentage: 2.23 },
          { value: '29.99', count: 15672, percentage: 1.85 },
        ],
        insights: [
          '47 transactions exceed $5,000 (potential fraud flag)',
          'Strong clustering around $99.99 price point',
          'Right-skewed distribution typical for e-commerce',
        ],
      },
      {
        name: 'postal_code',
        inferredType: 'string',
        declaredType: 'VARCHAR(10)',
        nullCount: 262661,
        nullPercentage: 31.0,
        uniqueCount: 8472,
        uniquePercentage: 1.0,
        healthScore: 51,
        flags: ['high_nulls', 'type_mismatch'],
        topValues: [
          { value: '90210', count: 4782, percentage: 0.56 },
          { value: '10001', count: 3891, percentage: 0.46 },
          { value: '60601', count: 3247, percentage: 0.38 },
        ],
        insights: [
          'High null rate (31%) limits geographic segmentation',
          'Mixed US/international formats detected',
          'Consider separate validation rules by country',
        ],
      },
      {
        name: 'customer_id',
        inferredType: 'integer',
        declaredType: 'BIGINT',
        nullCount: 0,
        nullPercentage: 0,
        uniqueCount: 234891,
        uniquePercentage: 27.72,
        healthScore: 94,
        flags: [],
        numericStats: {
          mean: 500234,
          median: 498723,
          stdDev: 144782,
          min: 100001,
          max: 899999,
          q25: 375891,
          q75: 624567,
        },
        distribution: {
          bins: [100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000],
          counts: [94782, 98234, 102891, 106723, 108934, 104782, 99847, 95234, 35866],
        },
        topValues: [
          { value: '100001', count: 1, percentage: 0.0001 },
          { value: '100002', count: 1, percentage: 0.0001 },
          { value: '100003', count: 1, percentage: 0.0001 },
        ],
        insights: [
          'Excellent uniqueness for primary key',
          'No nulls or duplicates detected',
          'Sequential ID pattern suggests auto-increment',
        ],
      },
      {
        name: 'transaction_date',
        inferredType: 'datetime',
        declaredType: 'TIMESTAMP',
        nullCount: 0,
        nullPercentage: 0,
        uniqueCount: 365,
        uniquePercentage: 0.04,
        healthScore: 89,
        flags: [],
        topValues: [
          { value: '2024-12-15', count: 8923, percentage: 1.05 },
          { value: '2024-11-29', count: 8472, percentage: 1.0 },
          { value: '2024-12-24', count: 7891, percentage: 0.93 },
        ],
        insights: [
          'Complete temporal coverage for 2024',
          'Peak activity on Black Friday and holiday season',
          'No future dates or obvious data entry errors',
        ],
      },
      {
        name: 'product_category',
        inferredType: 'categorical',
        declaredType: 'VARCHAR(50)',
        nullCount: 4782,
        nullPercentage: 0.56,
        uniqueCount: 12,
        uniquePercentage: 0.001,
        healthScore: 87,
        flags: ['low_cardinality'],
        topValues: [
          { value: 'Electronics', count: 234891, percentage: 27.72 },
          { value: 'Clothing', count: 187234, percentage: 22.09 },
          { value: 'Home & Garden', count: 142783, percentage: 16.85 },
          { value: 'Books', count: 98472, percentage: 11.62 },
          { value: 'Sports', count: 87234, percentage: 10.29 },
        ],
        insights: [
          'Well-defined categorical structure',
          'Electronics dominates with 28% of transactions',
          'Low null rate indicates good data capture',
        ],
      },
      {
        name: 'payment_method',
        inferredType: 'categorical',
        declaredType: 'VARCHAR(20)',
        nullCount: 0,
        nullPercentage: 0,
        uniqueCount: 5,
        uniquePercentage: 0.0006,
        healthScore: 96,
        flags: [],
        topValues: [
          { value: 'credit_card', count: 487234, percentage: 57.51 },
          { value: 'debit_card', count: 198472, percentage: 23.42 },
          { value: 'paypal', count: 98234, percentage: 11.59 },
          { value: 'apple_pay', count: 42891, percentage: 5.06 },
          { value: 'google_pay', count: 20462, percentage: 2.41 },
        ],
        insights: [
          'Credit cards dominate payment mix (58%)',
          'Digital wallets growing (18% combined)',
          'No missing or invalid payment methods',
        ],
      },
      {
        name: 'discount_code',
        inferredType: 'string',
        declaredType: 'VARCHAR(20)',
        nullCount: 678234,
        nullPercentage: 80.04,
        uniqueCount: 247,
        uniquePercentage: 0.03,
        healthScore: 78,
        flags: ['high_nulls'],
        topValues: [
          { value: 'SAVE20', count: 42891, percentage: 5.06 },
          { value: 'WELCOME10', count: 38472, percentage: 4.54 },
          { value: 'FREESHIP', count: 28934, percentage: 3.41 },
        ],
        insights: [
          'High null rate expected for optional field',
          '20% discount adoption rate',
          'Top 3 codes account for 13% of all transactions',
        ],
      },
      {
        name: 'shipping_country',
        inferredType: 'categorical',
        declaredType: 'CHAR(2)',
        nullCount: 8472,
        nullPercentage: 1.0,
        uniqueCount: 47,
        uniquePercentage: 0.006,
        healthScore: 91,
        flags: [],
        topValues: [
          { value: 'US', count: 623891, percentage: 73.63 },
          { value: 'CA', count: 98234, percentage: 11.59 },
          { value: 'GB', count: 47823, percentage: 5.64 },
          { value: 'AU', count: 28934, percentage: 3.41 },
          { value: 'DE', count: 18472, percentage: 2.18 },
        ],
        insights: [
          'US market dominates (74% of orders)',
          'ISO 3166-1 alpha-2 format consistently used',
          'Good geographic diversity across 47 countries',
        ],
      },
      {
        name: 'customer_segment',
        inferredType: 'categorical',
        declaredType: 'VARCHAR(20)',
        nullCount: 0,
        nullPercentage: 0,
        uniqueCount: 4,
        uniquePercentage: 0.0005,
        healthScore: 93,
        flags: [],
        topValues: [
          { value: 'Premium', count: 298472, percentage: 35.23 },
          { value: 'Standard', count: 287234, percentage: 33.90 },
          { value: 'Basic', count: 198234, percentage: 23.40 },
          { value: 'Trial', count: 63353, percentage: 7.48 },
        ],
        insights: [
          'Balanced distribution across segments',
          'Premium segment largest at 35%',
          'Trial conversion opportunity at 7.5%',
        ],
      },
      {
        name: 'order_status',
        inferredType: 'categorical',
        declaredType: 'VARCHAR(20)',
        nullCount: 0,
        nullPercentage: 0,
        uniqueCount: 6,
        uniquePercentage: 0.0007,
        healthScore: 88,
        flags: [],
        topValues: [
          { value: 'completed', count: 723891, percentage: 85.43 },
          { value: 'pending', count: 67234, percentage: 7.93 },
          { value: 'cancelled', count: 34782, percentage: 4.10 },
          { value: 'refunded', count: 15672, percentage: 1.85 },
          { value: 'failed', count: 5714, percentage: 0.67 },
        ],
        insights: [
          'High completion rate (85%) indicates healthy funnel',
          'Cancellation rate (4%) within industry norms',
          'Failed transactions (0.67%) suggest stable payment processing',
        ],
      },
    ],
  };
}

export async function simulateProcessing(): Promise<ProfileReport> {
  const delay = 1500 + Math.random() * 500;
  await new Promise(resolve => setTimeout(resolve, delay));
  return getMockReport();
}
